events {}
http {
  server {
    listen 80;
    location / {
      resolver 127.0.0.11 valid=5s;
      set $upstream http://lattice:3000;
      proxy_pass $upstream;
      proxy_buffering off;
      proxy_cache off;
      proxy_read_timeout 3600s;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      chunked_transfer_encoding on;
    }
  }
}
