events {}
http {
  upstream lattice {
    ip_hash;
    server lattice:3000;
  }
  server {
    listen 80;
    location / {
      proxy_pass http://lattice;
      proxy_buffering off;
      proxy_cache off;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      chunked_transfer_encoding on;
    }
  }
}
